/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/campaigns": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.campaigns.id"];
          user_id?: parameters["rowFilter.campaigns.user_id"];
          created_at?: parameters["rowFilter.campaigns.created_at"];
          name?: parameters["rowFilter.campaigns.name"];
          description?: parameters["rowFilter.campaigns.description"];
          toolbar?: parameters["rowFilter.campaigns.toolbar"];
          setting?: parameters["rowFilter.campaigns.setting"];
          overview?: parameters["rowFilter.campaigns.overview"];
          overview_plaintext?: parameters["rowFilter.campaigns.overview_plaintext"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["campaigns"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** campaigns */
          campaigns?: definitions["campaigns"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.campaigns.id"];
          user_id?: parameters["rowFilter.campaigns.user_id"];
          created_at?: parameters["rowFilter.campaigns.created_at"];
          name?: parameters["rowFilter.campaigns.name"];
          description?: parameters["rowFilter.campaigns.description"];
          toolbar?: parameters["rowFilter.campaigns.toolbar"];
          setting?: parameters["rowFilter.campaigns.setting"];
          overview?: parameters["rowFilter.campaigns.overview"];
          overview_plaintext?: parameters["rowFilter.campaigns.overview_plaintext"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.campaigns.id"];
          user_id?: parameters["rowFilter.campaigns.user_id"];
          created_at?: parameters["rowFilter.campaigns.created_at"];
          name?: parameters["rowFilter.campaigns.name"];
          description?: parameters["rowFilter.campaigns.description"];
          toolbar?: parameters["rowFilter.campaigns.toolbar"];
          setting?: parameters["rowFilter.campaigns.setting"];
          overview?: parameters["rowFilter.campaigns.overview"];
          overview_plaintext?: parameters["rowFilter.campaigns.overview_plaintext"];
        };
        body: {
          /** campaigns */
          campaigns?: definitions["campaigns"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/documents": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.documents.id"];
          user_id?: parameters["rowFilter.documents.user_id"];
          campaign_id?: parameters["rowFilter.documents.campaign_id"];
          created_at?: parameters["rowFilter.documents.created_at"];
          updated_at?: parameters["rowFilter.documents.updated_at"];
          name?: parameters["rowFilter.documents.name"];
          overview?: parameters["rowFilter.documents.overview"];
          overview_plaintext?: parameters["rowFilter.documents.overview_plaintext"];
          type?: parameters["rowFilter.documents.type"];
          tags?: parameters["rowFilter.documents.tags"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["documents"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** documents */
          documents?: definitions["documents"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.documents.id"];
          user_id?: parameters["rowFilter.documents.user_id"];
          campaign_id?: parameters["rowFilter.documents.campaign_id"];
          created_at?: parameters["rowFilter.documents.created_at"];
          updated_at?: parameters["rowFilter.documents.updated_at"];
          name?: parameters["rowFilter.documents.name"];
          overview?: parameters["rowFilter.documents.overview"];
          overview_plaintext?: parameters["rowFilter.documents.overview_plaintext"];
          type?: parameters["rowFilter.documents.type"];
          tags?: parameters["rowFilter.documents.tags"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.documents.id"];
          user_id?: parameters["rowFilter.documents.user_id"];
          campaign_id?: parameters["rowFilter.documents.campaign_id"];
          created_at?: parameters["rowFilter.documents.created_at"];
          updated_at?: parameters["rowFilter.documents.updated_at"];
          name?: parameters["rowFilter.documents.name"];
          overview?: parameters["rowFilter.documents.overview"];
          overview_plaintext?: parameters["rowFilter.documents.overview_plaintext"];
          type?: parameters["rowFilter.documents.type"];
          tags?: parameters["rowFilter.documents.tags"];
        };
        body: {
          /** documents */
          documents?: definitions["documents"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/events": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.events.id"];
          user_id?: parameters["rowFilter.events.user_id"];
          timeline_id?: parameters["rowFilter.events.timeline_id"];
          campaign_id?: parameters["rowFilter.events.campaign_id"];
          name?: parameters["rowFilter.events.name"];
          overview?: parameters["rowFilter.events.overview"];
          overview_plaintext?: parameters["rowFilter.events.overview_plaintext"];
          date?: parameters["rowFilter.events.date"];
          index?: parameters["rowFilter.events.index"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["events"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** events */
          events?: definitions["events"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.events.id"];
          user_id?: parameters["rowFilter.events.user_id"];
          timeline_id?: parameters["rowFilter.events.timeline_id"];
          campaign_id?: parameters["rowFilter.events.campaign_id"];
          name?: parameters["rowFilter.events.name"];
          overview?: parameters["rowFilter.events.overview"];
          overview_plaintext?: parameters["rowFilter.events.overview_plaintext"];
          date?: parameters["rowFilter.events.date"];
          index?: parameters["rowFilter.events.index"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.events.id"];
          user_id?: parameters["rowFilter.events.user_id"];
          timeline_id?: parameters["rowFilter.events.timeline_id"];
          campaign_id?: parameters["rowFilter.events.campaign_id"];
          name?: parameters["rowFilter.events.name"];
          overview?: parameters["rowFilter.events.overview"];
          overview_plaintext?: parameters["rowFilter.events.overview_plaintext"];
          date?: parameters["rowFilter.events.date"];
          index?: parameters["rowFilter.events.index"];
        };
        body: {
          /** events */
          events?: definitions["events"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/profile": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profile.id"];
          display_name?: parameters["rowFilter.profile.display_name"];
          email?: parameters["rowFilter.profile.email"];
          theme?: parameters["rowFilter.profile.theme"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["profile"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** profile */
          profile?: definitions["profile"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profile.id"];
          display_name?: parameters["rowFilter.profile.display_name"];
          email?: parameters["rowFilter.profile.email"];
          theme?: parameters["rowFilter.profile.theme"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profile.id"];
          display_name?: parameters["rowFilter.profile.display_name"];
          email?: parameters["rowFilter.profile.email"];
          theme?: parameters["rowFilter.profile.theme"];
        };
        body: {
          /** profile */
          profile?: definitions["profile"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/timelines": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.timelines.id"];
          user_id?: parameters["rowFilter.timelines.user_id"];
          campaign_id?: parameters["rowFilter.timelines.campaign_id"];
          name?: parameters["rowFilter.timelines.name"];
          overview?: parameters["rowFilter.timelines.overview"];
          overview_plaintext?: parameters["rowFilter.timelines.overview_plaintext"];
          updated_at?: parameters["rowFilter.timelines.updated_at"];
          tags?: parameters["rowFilter.timelines.tags"];
          created_at?: parameters["rowFilter.timelines.created_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["timelines"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** timelines */
          timelines?: definitions["timelines"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.timelines.id"];
          user_id?: parameters["rowFilter.timelines.user_id"];
          campaign_id?: parameters["rowFilter.timelines.campaign_id"];
          name?: parameters["rowFilter.timelines.name"];
          overview?: parameters["rowFilter.timelines.overview"];
          overview_plaintext?: parameters["rowFilter.timelines.overview_plaintext"];
          updated_at?: parameters["rowFilter.timelines.updated_at"];
          tags?: parameters["rowFilter.timelines.tags"];
          created_at?: parameters["rowFilter.timelines.created_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.timelines.id"];
          user_id?: parameters["rowFilter.timelines.user_id"];
          campaign_id?: parameters["rowFilter.timelines.campaign_id"];
          name?: parameters["rowFilter.timelines.name"];
          overview?: parameters["rowFilter.timelines.overview"];
          overview_plaintext?: parameters["rowFilter.timelines.overview_plaintext"];
          updated_at?: parameters["rowFilter.timelines.updated_at"];
          tags?: parameters["rowFilter.timelines.tags"];
          created_at?: parameters["rowFilter.timelines.created_at"];
        };
        body: {
          /** timelines */
          timelines?: definitions["timelines"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/rpc/search_documents": {
    post: {
      parameters: {
        body: {
          args: {
            /** Format: character varying */
            document_term: string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/show_limit": {
    post: {
      parameters: {
        body: {
          args: { [key: string]: unknown };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/show_trgm": {
    post: {
      parameters: {
        body: {
          args: {
            /** Format: text */
            "": string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
}

export interface definitions {
  campaigns: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default extensions.uuid_generate_v4()
     */
    id: string;
    /**
     * Format: uuid
     * @default auth.uid()
     */
    user_id: string;
    /**
     * Format: timestamp with time zone
     * @default (now() AT TIME ZONE 'utc'::text)
     */
    created_at: string;
    /**
     * Format: text
     * @default Campaign Name
     */
    name: string;
    /**
     * Format: text
     * @default Campaign description.
     */
    description: string;
    /**
     * Format: text
     * @default bottom
     */
    toolbar: string;
    /** Format: text */
    setting?: string;
    /** Format: jsonb */
    overview?: string;
    /** Format: text */
    overview_plaintext?: string;
  };
  documents: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default extensions.uuid_generate_v4()
     */
    id: string;
    /**
     * Format: uuid
     * @default auth.uid()
     */
    user_id: string;
    /** Format: uuid */
    campaign_id: string;
    /**
     * Format: timestamp with time zone
     * @default timezone('utc'::text, now())
     */
    created_at: string;
    /**
     * Format: timestamp with time zone
     * @default timezone('utc'::text, now())
     */
    updated_at: string;
    /** Format: text */
    name?: string;
    /** Format: jsonb */
    overview?: string;
    /** Format: text */
    overview_plaintext?: string;
    /**
     * Format: text
     * @default other
     */
    type: string;
    /** Format: ARRAY */
    tags?: unknown[];
  };
  events: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default extensions.uuid_generate_v4()
     */
    id: string;
    /**
     * Format: uuid
     * @default auth.uid()
     */
    user_id: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `timelines.id`.<fk table='timelines' column='id'/>
     */
    timeline_id: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `campaigns.id`.<fk table='campaigns' column='id'/>
     */
    campaign_id: string;
    /** Format: text */
    name?: string;
    /** Format: jsonb */
    overview?: string;
    /** Format: text */
    overview_plaintext?: string;
    /** Format: bigint */
    date: number;
    /** Format: integer */
    index?: number;
  };
  profile: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /** Format: text */
    display_name: string;
    /** Format: text */
    email?: string;
    /** Format: text */
    theme?: string;
  };
  timelines: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default extensions.uuid_generate_v4()
     */
    id: string;
    /**
     * Format: uuid
     * @default auth.uid()
     */
    user_id: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `campaigns.id`.<fk table='campaigns' column='id'/>
     */
    campaign_id: string;
    /** Format: text */
    name?: string;
    /** Format: jsonb */
    overview?: string;
    /** Format: text */
    overview_plaintext?: string;
    /**
     * Format: timestamp with time zone
     * @default (now() AT TIME ZONE 'utc'::text)
     */
    updated_at?: string;
    /** Format: ARRAY */
    tags?: unknown[];
    /**
     * Format: timestamp with time zone
     * @default (now() AT TIME ZONE 'utc'::text)
     */
    created_at: string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description campaigns */
  "body.campaigns": definitions["campaigns"];
  /** Format: uuid */
  "rowFilter.campaigns.id": string;
  /** Format: uuid */
  "rowFilter.campaigns.user_id": string;
  /** Format: timestamp with time zone */
  "rowFilter.campaigns.created_at": string;
  /** Format: text */
  "rowFilter.campaigns.name": string;
  /** Format: text */
  "rowFilter.campaigns.description": string;
  /** Format: text */
  "rowFilter.campaigns.toolbar": string;
  /** Format: text */
  "rowFilter.campaigns.setting": string;
  /** Format: jsonb */
  "rowFilter.campaigns.overview": string;
  /** Format: text */
  "rowFilter.campaigns.overview_plaintext": string;
  /** @description documents */
  "body.documents": definitions["documents"];
  /** Format: uuid */
  "rowFilter.documents.id": string;
  /** Format: uuid */
  "rowFilter.documents.user_id": string;
  /** Format: uuid */
  "rowFilter.documents.campaign_id": string;
  /** Format: timestamp with time zone */
  "rowFilter.documents.created_at": string;
  /** Format: timestamp with time zone */
  "rowFilter.documents.updated_at": string;
  /** Format: text */
  "rowFilter.documents.name": string;
  /** Format: jsonb */
  "rowFilter.documents.overview": string;
  /** Format: text */
  "rowFilter.documents.overview_plaintext": string;
  /** Format: text */
  "rowFilter.documents.type": string;
  /** Format: ARRAY */
  "rowFilter.documents.tags": string;
  /** @description events */
  "body.events": definitions["events"];
  /** Format: uuid */
  "rowFilter.events.id": string;
  /** Format: uuid */
  "rowFilter.events.user_id": string;
  /** Format: uuid */
  "rowFilter.events.timeline_id": string;
  /** Format: uuid */
  "rowFilter.events.campaign_id": string;
  /** Format: text */
  "rowFilter.events.name": string;
  /** Format: jsonb */
  "rowFilter.events.overview": string;
  /** Format: text */
  "rowFilter.events.overview_plaintext": string;
  /** Format: bigint */
  "rowFilter.events.date": string;
  /** Format: integer */
  "rowFilter.events.index": string;
  /** @description profile */
  "body.profile": definitions["profile"];
  /** Format: uuid */
  "rowFilter.profile.id": string;
  /** Format: text */
  "rowFilter.profile.display_name": string;
  /** Format: text */
  "rowFilter.profile.email": string;
  /** Format: text */
  "rowFilter.profile.theme": string;
  /** @description timelines */
  "body.timelines": definitions["timelines"];
  /** Format: uuid */
  "rowFilter.timelines.id": string;
  /** Format: uuid */
  "rowFilter.timelines.user_id": string;
  /** Format: uuid */
  "rowFilter.timelines.campaign_id": string;
  /** Format: text */
  "rowFilter.timelines.name": string;
  /** Format: jsonb */
  "rowFilter.timelines.overview": string;
  /** Format: text */
  "rowFilter.timelines.overview_plaintext": string;
  /** Format: timestamp with time zone */
  "rowFilter.timelines.updated_at": string;
  /** Format: ARRAY */
  "rowFilter.timelines.tags": string;
  /** Format: timestamp with time zone */
  "rowFilter.timelines.created_at": string;
}

export interface operations {}

export interface external {}
